version: '3'

services:
  web:
    container_name: web
    build:
      context: docker/server
      dockerfile: Dockerfile
    volumes:
      - ".:/menu-web"
      - "./node_modules:/menu-web/node_modules"
      - "./package.json:/menu-web/package.json"
      - "./package-lock.json:/menu-web/package-lock.json"
    ports:
      - '8001:8080'
